---
- name: Render zabbix_agent2.conf
  ansible.builtin.template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix
    group: zabbix
    mode: '0644'
  notify: Restart zabbix-agent2
  register: agent_cfg

- name: Create dir for custom scripts
  ansible.builtin.file:
    path: /etc/zabbix/zabbix_agent2.d/customscripts.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Validate agent config (syntax)
  ansible.builtin.command: "zabbix_agent2 -T -c /etc/zabbix/zabbix_agent2.conf"
  changed_when: false
  when: agent_cfg is changed or (agent_psk is defined and agent_psk is changed)
  become: true
