- name: Install agent
  ansible.builtin.import_tasks: 
    file: install_agent2.yml
  tags: install-zabbix

- name: Configure agent
  ansible.builtin.import_tasks: 
    file: configure_agent2.yml
  tags: config-zabbix
