---
- name: Configure Zabbix Agent
  ansible.builtin.template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix
    group: zabbix
    mode: '0644'
  when: "'zabbix-agent2' in zabbix_packages"
  become: yes

- name: Create zabbix-agent.key file from template
  ansible.builtin.template:
    src: zabbix-agent.key.j2
    dest: /etc/zabbix/zabbix-agent.key
    owner: zabbix
    group: root
    mode: '0644'
  become: yes

- name: Ensure Zabbix Agent is enabled and started
  ansible.builtin.service:
    name: zabbix-agent2
    enabled: yes
    state: restarted
  when: "'zabbix-agent2' in zabbix_packages"
  become: yes
