---
- name: Download Zabbix repo key
  ansible.builtin.get_url:
    url: "{{ zabbix_repo_key }}"
    dest: /usr/share/keyrings/zabbix-archive-keyring.gpg
  become: yes
  register: zabbix_repo_key_download
  until: zabbix_repo_key_download is succeeded
  changed_when: False

- name: Detect Ubuntu version
  ansible.builtin.command: lsb_release -sr
  register: ubuntu_version
  changed_when: False

- name: Download Zabbix release package
  ansible.builtin.command: >
    wget https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu{{ ubuntu_version.stdout }}_all.deb -O /tmp/zabbix-release.deb
  become: yes

- name: Install Zabbix release package
  ansible.builtin.command: dpkg -i /tmp/zabbix-release.deb
  become: yes

- name: Add Zabbix repository
  ansible.builtin.apt_repository:
    repo: "{{ zabbix_repo }}"
    filename: 'zabbix'
    state: present
  become: yes
  register: add_zabbix_repo
  until: add_zabbix_repo is succeeded

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes
  when: add_zabbix_repo.changed

- name: Install Zabbix packages
  ansible.builtin.apt:
    name: "{{ zabbix_packages }}"
    state: present
  become: yes
