---
- name: Check if OS is Debian or Ubuntu
  set_fact:
    is_debian_or_ubuntu: "{{ ansible_facts['os_family'] == 'Debian' }}"

- name: Ensure Wazuh GPG key is imported
  apt_key:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present
    keyring: /usr/share/keyrings/wazuh.gpg
  when: is_debian_or_ubuntu

- name: Add Wazuh repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main
    filename: wazuh
  when: is_debian_or_ubuntu

- name: Update apt cache
  apt:
    update_cache: yes
  when: is_debian_or_ubuntu

- name: Install Wazuh agent
  apt:
    name: wazuh-agent
    state: present
  environment:
    WAZUH_MANAGER: "wazuh.redgelabs.com"
  when: is_debian_or_ubuntu

- name: Enable and start Wazuh agent service
  systemd:
    name: wazuh-agent
    enabled: yes
    state: started
  when: is_debian_or_ubuntu
